apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
          - tunnel
          - run
          - --token
          - "$(TOKEN)"
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: cf-tokens
                key: tunnel
