apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-workbench
  template:
    metadata:
      labels:
        app: etcd-workbench
    spec:
      containers:
        - name: etcd-workbench
          image: tzfun/etcd-workbench:latest
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-workbench
spec:
  type: ClusterIP
  selector:
    app: etcd-workbench
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: etcd-workbench
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  rules:
    - host: etcd.$DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: etcd-workbench
                port:
                  number: 8002
