{{- $name := .Release.Name -}}
{{- if .Values.databases }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-init
data:
  init.sql: |
    {{- range .Values.databases }}
    {{- $user := .user | default .name }}
    -- 創建用戶 {{ $user }}
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '{{ $user }}') THEN
        {{- if .password }}
        CREATE USER {{ $user }} WITH PASSWORD '{{ .password }}';
        {{- else }}
        CREATE USER {{ $user }};
        {{- end }}
      END IF;
    END
    $$;

    -- 創建資料庫 {{ .name }}
    SELECT 'CREATE DATABASE {{ .name }} OWNER {{ $user }}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{ .name }}')\gexec

    -- 賦予權限
    GRANT ALL PRIVILEGES ON DATABASE {{ .name }} TO {{ $user }};
    \c {{ .name }}
    GRANT ALL ON SCHEMA public TO {{ $user }};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO {{ $user }};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO {{ $user }};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO {{ $user }};
    {{- end }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: {{ $name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
spec:
  serviceName: {{ $name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: postgresql
          image: "postgres:{{ .Chart.AppVersion }}-bookworm"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.auth.username | quote }}
            {{- if .Values.auth.password }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.auth.password | quote }}
            {{- else }}
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            {{- end }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            {{- if .Values.databases }}
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.databases }}
      volumes:
        - name: init-scripts
          configMap:
            name: {{ $name }}-init
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.size }}

